# Generated by Django 5.1.6 on 2025-03-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_category_url_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categgory',
            new_name='category',
        ),
    ]
